using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace DianDang
{
    /// <summary>
    /// Controller class for DDRoles
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class DDRoleController
    {
        // Preload our schema..
        DDRole thisSchemaLoad = new DDRole();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public DDRoleCollection FetchAll()
        {
            DDRoleCollection coll = new DDRoleCollection();
            Query qry = new Query(DDRole.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public DDRoleCollection FetchByID(object RoleID)
        {
            DDRoleCollection coll = new DDRoleCollection().Where("RoleID", RoleID).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public DDRoleCollection FetchByQuery(Query qry)
        {
            DDRoleCollection coll = new DDRoleCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object RoleID)
        {
            return (DDRole.Delete(RoleID) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object RoleID)
        {
            return (DDRole.Destroy(RoleID) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(string RoleName)
	    {
		    DDRole item = new DDRole();
		    
            item.RoleName = RoleName;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(int RoleID,string RoleName)
	    {
		    DDRole item = new DDRole();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.RoleID = RoleID;
				
			item.RoleName = RoleName;
				
	        item.Save(UserName);
	    }
    }
}
