using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace DianDang
{
    /// <summary>
    /// Controller class for DDTicketStatus
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class DDTicketStatusController
    {
        // Preload our schema..
        DDTicketStatus thisSchemaLoad = new DDTicketStatus();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public DDTicketStatusCollection FetchAll()
        {
            DDTicketStatusCollection coll = new DDTicketStatusCollection();
            Query qry = new Query(DDTicketStatus.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public DDTicketStatusCollection FetchByID(object StatusID)
        {
            DDTicketStatusCollection coll = new DDTicketStatusCollection().Where("StatusID", StatusID).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public DDTicketStatusCollection FetchByQuery(Query qry)
        {
            DDTicketStatusCollection coll = new DDTicketStatusCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object StatusID)
        {
            return (DDTicketStatus.Delete(StatusID) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object StatusID)
        {
            return (DDTicketStatus.Destroy(StatusID) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(string Description,int? Visible,int? IsOperation)
	    {
		    DDTicketStatus item = new DDTicketStatus();
		    
            item.Description = Description;
            
            item.Visible = Visible;
            
            item.IsOperation = IsOperation;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(int StatusID,string Description,int? Visible,int? IsOperation)
	    {
		    DDTicketStatus item = new DDTicketStatus();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.StatusID = StatusID;
				
			item.Description = Description;
				
			item.Visible = Visible;
				
			item.IsOperation = IsOperation;
				
	        item.Save(UserName);
	    }
    }
}
