using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace DianDang
{
	/// <summary>
	/// Strongly-typed collection for the DDPawnageClass class.
	/// </summary>
    [Serializable]
	public partial class DDPawnageClassCollection : ActiveList<DDPawnageClass, DDPawnageClassCollection>
	{	   
		public DDPawnageClassCollection() {}
        
        /// <summary>
		/// Filters an existing collection based on the set criteria. This is an in-memory filter
		/// Thanks to developingchris for this!
        /// </summary>
        /// <returns>DDPawnageClassCollection</returns>
		public DDPawnageClassCollection Filter()
        {
            for (int i = this.Count - 1; i > -1; i--)
            {
                DDPawnageClass o = this[i];
                foreach (SubSonic.Where w in this.wheres)
                {
                    bool remove = false;
                    System.Reflection.PropertyInfo pi = o.GetType().GetProperty(w.ColumnName);
                    if (pi.CanRead)
                    {
                        object val = pi.GetValue(o, null);
                        switch (w.Comparison)
                        {
                            case SubSonic.Comparison.Equals:
                                if (!val.Equals(w.ParameterValue))
                                {
                                    remove = true;
                                }
                                break;
                        }
                    }
                    if (remove)
                    {
                        this.Remove(o);
                        break;
                    }
                }
            }
            return this;
        }
		
		
	}
	/// <summary>
	/// This is an ActiveRecord class which wraps the DDPawnageClass table.
	/// </summary>
	[Serializable]
	public partial class DDPawnageClass : ActiveRecord<DDPawnageClass>, IActiveRecord
	{
		#region .ctors and Default Settings
		
		public DDPawnageClass()
		{
		  SetSQLProps();
		  InitSetDefaults();
		  MarkNew();
		}
		
		private void InitSetDefaults() { SetDefaults(); }
		
		public DDPawnageClass(bool useDatabaseDefaults)
		{
			SetSQLProps();
			if(useDatabaseDefaults)
				ForceDefaults();
			MarkNew();
		}
        
		public DDPawnageClass(object keyID)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByKey(keyID);
		}
		 
		public DDPawnageClass(string columnName, object columnValue)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByParam(columnName,columnValue);
		}
		
		protected static void SetSQLProps() { GetTableSchema(); }
		
		#endregion
		
		#region Schema and Query Accessor	
		public static Query CreateQuery() { return new Query(Schema); }
		public static TableSchema.Table Schema
		{
			get
			{
				if (BaseSchema == null)
					SetSQLProps();
				return BaseSchema;
			}
		}
		
		private static void GetTableSchema() 
		{
			if(!IsSchemaInitialized)
			{
				//Schema declaration
				TableSchema.Table schema = new TableSchema.Table("DDPawnageClass", TableType.Table, DataService.GetInstance("DianDang"));
				schema.Columns = new TableSchema.TableColumnCollection();
				schema.SchemaName = @"dbo";
				//columns
				
				TableSchema.TableColumn colvarClassID = new TableSchema.TableColumn(schema);
				colvarClassID.ColumnName = "ClassID";
				colvarClassID.DataType = DbType.Int32;
				colvarClassID.MaxLength = 0;
				colvarClassID.AutoIncrement = true;
				colvarClassID.IsNullable = false;
				colvarClassID.IsPrimaryKey = true;
				colvarClassID.IsForeignKey = false;
				colvarClassID.IsReadOnly = false;
				colvarClassID.DefaultSetting = @"";
				colvarClassID.ForeignKeyTableName = "";
				schema.Columns.Add(colvarClassID);
				
				TableSchema.TableColumn colvarClassName = new TableSchema.TableColumn(schema);
				colvarClassName.ColumnName = "ClassName";
				colvarClassName.DataType = DbType.AnsiString;
				colvarClassName.MaxLength = 50;
				colvarClassName.AutoIncrement = false;
				colvarClassName.IsNullable = true;
				colvarClassName.IsPrimaryKey = false;
				colvarClassName.IsForeignKey = false;
				colvarClassName.IsReadOnly = false;
				colvarClassName.DefaultSetting = @"";
				colvarClassName.ForeignKeyTableName = "";
				schema.Columns.Add(colvarClassName);
				
				TableSchema.TableColumn colvarParentID = new TableSchema.TableColumn(schema);
				colvarParentID.ColumnName = "ParentID";
				colvarParentID.DataType = DbType.Int32;
				colvarParentID.MaxLength = 0;
				colvarParentID.AutoIncrement = false;
				colvarParentID.IsNullable = true;
				colvarParentID.IsPrimaryKey = false;
				colvarParentID.IsForeignKey = false;
				colvarParentID.IsReadOnly = false;
				
						colvarParentID.DefaultSetting = @"(0)";
				colvarParentID.ForeignKeyTableName = "";
				schema.Columns.Add(colvarParentID);
				
				TableSchema.TableColumn colvarUnitID = new TableSchema.TableColumn(schema);
				colvarUnitID.ColumnName = "UnitID";
				colvarUnitID.DataType = DbType.Int32;
				colvarUnitID.MaxLength = 0;
				colvarUnitID.AutoIncrement = false;
				colvarUnitID.IsNullable = true;
				colvarUnitID.IsPrimaryKey = false;
				colvarUnitID.IsForeignKey = false;
				colvarUnitID.IsReadOnly = false;
				colvarUnitID.DefaultSetting = @"";
				colvarUnitID.ForeignKeyTableName = "";
				schema.Columns.Add(colvarUnitID);
				
				TableSchema.TableColumn colvarMonthFeeRate = new TableSchema.TableColumn(schema);
				colvarMonthFeeRate.ColumnName = "MonthFeeRate";
				colvarMonthFeeRate.DataType = DbType.AnsiString;
				colvarMonthFeeRate.MaxLength = 50;
				colvarMonthFeeRate.AutoIncrement = false;
				colvarMonthFeeRate.IsNullable = true;
				colvarMonthFeeRate.IsPrimaryKey = false;
				colvarMonthFeeRate.IsForeignKey = false;
				colvarMonthFeeRate.IsReadOnly = false;
				colvarMonthFeeRate.DefaultSetting = @"";
				colvarMonthFeeRate.ForeignKeyTableName = "";
				schema.Columns.Add(colvarMonthFeeRate);
				
				TableSchema.TableColumn colvarInterestRate = new TableSchema.TableColumn(schema);
				colvarInterestRate.ColumnName = "InterestRate";
				colvarInterestRate.DataType = DbType.AnsiString;
				colvarInterestRate.MaxLength = 50;
				colvarInterestRate.AutoIncrement = false;
				colvarInterestRate.IsNullable = true;
				colvarInterestRate.IsPrimaryKey = false;
				colvarInterestRate.IsForeignKey = false;
				colvarInterestRate.IsReadOnly = false;
				colvarInterestRate.DefaultSetting = @"";
				colvarInterestRate.ForeignKeyTableName = "";
				schema.Columns.Add(colvarInterestRate);
				
				TableSchema.TableColumn colvarDescription = new TableSchema.TableColumn(schema);
				colvarDescription.ColumnName = "Description";
				colvarDescription.DataType = DbType.AnsiString;
				colvarDescription.MaxLength = 50;
				colvarDescription.AutoIncrement = false;
				colvarDescription.IsNullable = true;
				colvarDescription.IsPrimaryKey = false;
				colvarDescription.IsForeignKey = false;
				colvarDescription.IsReadOnly = false;
				colvarDescription.DefaultSetting = @"";
				colvarDescription.ForeignKeyTableName = "";
				schema.Columns.Add(colvarDescription);
				
				TableSchema.TableColumn colvarIsRoot = new TableSchema.TableColumn(schema);
				colvarIsRoot.ColumnName = "IsRoot";
				colvarIsRoot.DataType = DbType.Int32;
				colvarIsRoot.MaxLength = 0;
				colvarIsRoot.AutoIncrement = false;
				colvarIsRoot.IsNullable = true;
				colvarIsRoot.IsPrimaryKey = false;
				colvarIsRoot.IsForeignKey = false;
				colvarIsRoot.IsReadOnly = false;
				colvarIsRoot.DefaultSetting = @"";
				colvarIsRoot.ForeignKeyTableName = "";
				schema.Columns.Add(colvarIsRoot);
				
				TableSchema.TableColumn colvarStatisticClassID = new TableSchema.TableColumn(schema);
				colvarStatisticClassID.ColumnName = "StatisticClassID";
				colvarStatisticClassID.DataType = DbType.Int32;
				colvarStatisticClassID.MaxLength = 0;
				colvarStatisticClassID.AutoIncrement = false;
				colvarStatisticClassID.IsNullable = true;
				colvarStatisticClassID.IsPrimaryKey = false;
				colvarStatisticClassID.IsForeignKey = false;
				colvarStatisticClassID.IsReadOnly = false;
				colvarStatisticClassID.DefaultSetting = @"";
				colvarStatisticClassID.ForeignKeyTableName = "";
				schema.Columns.Add(colvarStatisticClassID);
				
				BaseSchema = schema;
				//add this schema to the provider
				//so we can query it later
				DataService.Providers["DianDang"].AddSchema("DDPawnageClass",schema);
			}
		}
		#endregion
		
		#region Props
		  
		[XmlAttribute("ClassID")]
		[Bindable(true)]
		public int ClassID 
		{
			get { return GetColumnValue<int>(Columns.ClassID); }
			set { SetColumnValue(Columns.ClassID, value); }
		}
		  
		[XmlAttribute("ClassName")]
		[Bindable(true)]
		public string ClassName 
		{
			get { return GetColumnValue<string>(Columns.ClassName); }
			set { SetColumnValue(Columns.ClassName, value); }
		}
		  
		[XmlAttribute("ParentID")]
		[Bindable(true)]
		public int? ParentID 
		{
			get { return GetColumnValue<int?>(Columns.ParentID); }
			set { SetColumnValue(Columns.ParentID, value); }
		}
		  
		[XmlAttribute("UnitID")]
		[Bindable(true)]
		public int? UnitID 
		{
			get { return GetColumnValue<int?>(Columns.UnitID); }
			set { SetColumnValue(Columns.UnitID, value); }
		}
		  
		[XmlAttribute("MonthFeeRate")]
		[Bindable(true)]
		public string MonthFeeRate 
		{
			get { return GetColumnValue<string>(Columns.MonthFeeRate); }
			set { SetColumnValue(Columns.MonthFeeRate, value); }
		}
		  
		[XmlAttribute("InterestRate")]
		[Bindable(true)]
		public string InterestRate 
		{
			get { return GetColumnValue<string>(Columns.InterestRate); }
			set { SetColumnValue(Columns.InterestRate, value); }
		}
		  
		[XmlAttribute("Description")]
		[Bindable(true)]
		public string Description 
		{
			get { return GetColumnValue<string>(Columns.Description); }
			set { SetColumnValue(Columns.Description, value); }
		}
		  
		[XmlAttribute("IsRoot")]
		[Bindable(true)]
		public int? IsRoot 
		{
			get { return GetColumnValue<int?>(Columns.IsRoot); }
			set { SetColumnValue(Columns.IsRoot, value); }
		}
		  
		[XmlAttribute("StatisticClassID")]
		[Bindable(true)]
		public int? StatisticClassID 
		{
			get { return GetColumnValue<int?>(Columns.StatisticClassID); }
			set { SetColumnValue(Columns.StatisticClassID, value); }
		}
		
		#endregion
		
		
			
		
		//no foreign key tables defined (0)
		
		
		
		//no ManyToMany tables defined (0)
		
        
        
		#region ObjectDataSource support
		
		
		/// <summary>
		/// Inserts a record, can be used with the Object Data Source
		/// </summary>
		public static void Insert(string varClassName,int? varParentID,int? varUnitID,string varMonthFeeRate,string varInterestRate,string varDescription,int? varIsRoot,int? varStatisticClassID)
		{
			DDPawnageClass item = new DDPawnageClass();
			
			item.ClassName = varClassName;
			
			item.ParentID = varParentID;
			
			item.UnitID = varUnitID;
			
			item.MonthFeeRate = varMonthFeeRate;
			
			item.InterestRate = varInterestRate;
			
			item.Description = varDescription;
			
			item.IsRoot = varIsRoot;
			
			item.StatisticClassID = varStatisticClassID;
			
		
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		
		/// <summary>
		/// Updates a record, can be used with the Object Data Source
		/// </summary>
		public static void Update(int varClassID,string varClassName,int? varParentID,int? varUnitID,string varMonthFeeRate,string varInterestRate,string varDescription,int? varIsRoot,int? varStatisticClassID)
		{
			DDPawnageClass item = new DDPawnageClass();
			
				item.ClassID = varClassID;
			
				item.ClassName = varClassName;
			
				item.ParentID = varParentID;
			
				item.UnitID = varUnitID;
			
				item.MonthFeeRate = varMonthFeeRate;
			
				item.InterestRate = varInterestRate;
			
				item.Description = varDescription;
			
				item.IsRoot = varIsRoot;
			
				item.StatisticClassID = varStatisticClassID;
			
			item.IsNew = false;
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		#endregion
        
        
        
        #region Typed Columns
        
        
        public static TableSchema.TableColumn ClassIDColumn
        {
            get { return Schema.Columns[0]; }
        }
        
        
        
        public static TableSchema.TableColumn ClassNameColumn
        {
            get { return Schema.Columns[1]; }
        }
        
        
        
        public static TableSchema.TableColumn ParentIDColumn
        {
            get { return Schema.Columns[2]; }
        }
        
        
        
        public static TableSchema.TableColumn UnitIDColumn
        {
            get { return Schema.Columns[3]; }
        }
        
        
        
        public static TableSchema.TableColumn MonthFeeRateColumn
        {
            get { return Schema.Columns[4]; }
        }
        
        
        
        public static TableSchema.TableColumn InterestRateColumn
        {
            get { return Schema.Columns[5]; }
        }
        
        
        
        public static TableSchema.TableColumn DescriptionColumn
        {
            get { return Schema.Columns[6]; }
        }
        
        
        
        public static TableSchema.TableColumn IsRootColumn
        {
            get { return Schema.Columns[7]; }
        }
        
        
        
        public static TableSchema.TableColumn StatisticClassIDColumn
        {
            get { return Schema.Columns[8]; }
        }
        
        
        
        #endregion
		#region Columns Struct
		public struct Columns
		{
			 public static string ClassID = @"ClassID";
			 public static string ClassName = @"ClassName";
			 public static string ParentID = @"ParentID";
			 public static string UnitID = @"UnitID";
			 public static string MonthFeeRate = @"MonthFeeRate";
			 public static string InterestRate = @"InterestRate";
			 public static string Description = @"Description";
			 public static string IsRoot = @"IsRoot";
			 public static string StatisticClassID = @"StatisticClassID";
						
		}
		#endregion
		
		#region Update PK Collections
		
        #endregion
    
        #region Deep Save
		
        #endregion
	}
}
