using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace DianDang
{
    /// <summary>
    /// Controller class for DDModules
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class DDModuleController
    {
        // Preload our schema..
        DDModule thisSchemaLoad = new DDModule();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public DDModuleCollection FetchAll()
        {
            DDModuleCollection coll = new DDModuleCollection();
            Query qry = new Query(DDModule.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public DDModuleCollection FetchByID(object ModuleID)
        {
            DDModuleCollection coll = new DDModuleCollection().Where("ModuleID", ModuleID).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public DDModuleCollection FetchByQuery(Query qry)
        {
            DDModuleCollection coll = new DDModuleCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object ModuleID)
        {
            return (DDModule.Delete(ModuleID) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object ModuleID)
        {
            return (DDModule.Destroy(ModuleID) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(string ModuleName)
	    {
		    DDModule item = new DDModule();
		    
            item.ModuleName = ModuleName;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(int ModuleID,string ModuleName)
	    {
		    DDModule item = new DDModule();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.ModuleID = ModuleID;
				
			item.ModuleName = ModuleName;
				
	        item.Save(UserName);
	    }
    }
}
