using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace DianDang
{
    /// <summary>
    /// Controller class for DDPermissions
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class DDPermissionController
    {
        // Preload our schema..
        DDPermission thisSchemaLoad = new DDPermission();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public DDPermissionCollection FetchAll()
        {
            DDPermissionCollection coll = new DDPermissionCollection();
            Query qry = new Query(DDPermission.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public DDPermissionCollection FetchByID(object RoleID)
        {
            DDPermissionCollection coll = new DDPermissionCollection().Where("RoleID", RoleID).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public DDPermissionCollection FetchByQuery(Query qry)
        {
            DDPermissionCollection coll = new DDPermissionCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object RoleID)
        {
            return (DDPermission.Delete(RoleID) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object RoleID)
        {
            return (DDPermission.Destroy(RoleID) == 1);
        }
        
        
        
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(int RoleID,int ModuleID)
        {
            Query qry = new Query(DDPermission.Schema);
            qry.QueryType = QueryType.Delete;
            qry.AddWhere("RoleID", RoleID).AND("ModuleID", ModuleID);
            qry.Execute();
            return (true);
        }        
       
    	
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(int RoleID,int ModuleID,int? Flag)
	    {
		    DDPermission item = new DDPermission();
		    
            item.RoleID = RoleID;
            
            item.ModuleID = ModuleID;
            
            item.Flag = Flag;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(int RoleID,int ModuleID,int? Flag)
	    {
		    DDPermission item = new DDPermission();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.RoleID = RoleID;
				
			item.ModuleID = ModuleID;
				
			item.Flag = Flag;
				
	        item.Save(UserName);
	    }
    }
}
