using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace DianDang
{
	/// <summary>
	/// Strongly-typed collection for the DDCertType class.
	/// </summary>
    [Serializable]
	public partial class DDCertTypeCollection : ActiveList<DDCertType, DDCertTypeCollection>
	{	   
		public DDCertTypeCollection() {}
        
        /// <summary>
		/// Filters an existing collection based on the set criteria. This is an in-memory filter
		/// Thanks to developingchris for this!
        /// </summary>
        /// <returns>DDCertTypeCollection</returns>
		public DDCertTypeCollection Filter()
        {
            for (int i = this.Count - 1; i > -1; i--)
            {
                DDCertType o = this[i];
                foreach (SubSonic.Where w in this.wheres)
                {
                    bool remove = false;
                    System.Reflection.PropertyInfo pi = o.GetType().GetProperty(w.ColumnName);
                    if (pi.CanRead)
                    {
                        object val = pi.GetValue(o, null);
                        switch (w.Comparison)
                        {
                            case SubSonic.Comparison.Equals:
                                if (!val.Equals(w.ParameterValue))
                                {
                                    remove = true;
                                }
                                break;
                        }
                    }
                    if (remove)
                    {
                        this.Remove(o);
                        break;
                    }
                }
            }
            return this;
        }
		
		
	}
	/// <summary>
	/// This is an ActiveRecord class which wraps the DDCertTypes table.
	/// </summary>
	[Serializable]
	public partial class DDCertType : ActiveRecord<DDCertType>, IActiveRecord
	{
		#region .ctors and Default Settings
		
		public DDCertType()
		{
		  SetSQLProps();
		  InitSetDefaults();
		  MarkNew();
		}
		
		private void InitSetDefaults() { SetDefaults(); }
		
		public DDCertType(bool useDatabaseDefaults)
		{
			SetSQLProps();
			if(useDatabaseDefaults)
				ForceDefaults();
			MarkNew();
		}
        
		public DDCertType(object keyID)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByKey(keyID);
		}
		 
		public DDCertType(string columnName, object columnValue)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByParam(columnName,columnValue);
		}
		
		protected static void SetSQLProps() { GetTableSchema(); }
		
		#endregion
		
		#region Schema and Query Accessor	
		public static Query CreateQuery() { return new Query(Schema); }
		public static TableSchema.Table Schema
		{
			get
			{
				if (BaseSchema == null)
					SetSQLProps();
				return BaseSchema;
			}
		}
		
		private static void GetTableSchema() 
		{
			if(!IsSchemaInitialized)
			{
				//Schema declaration
				TableSchema.Table schema = new TableSchema.Table("DDCertTypes", TableType.Table, DataService.GetInstance("DianDang"));
				schema.Columns = new TableSchema.TableColumnCollection();
				schema.SchemaName = @"dbo";
				//columns
				
				TableSchema.TableColumn colvarTypeID = new TableSchema.TableColumn(schema);
				colvarTypeID.ColumnName = "TypeID";
				colvarTypeID.DataType = DbType.Int32;
				colvarTypeID.MaxLength = 0;
				colvarTypeID.AutoIncrement = true;
				colvarTypeID.IsNullable = false;
				colvarTypeID.IsPrimaryKey = true;
				colvarTypeID.IsForeignKey = false;
				colvarTypeID.IsReadOnly = false;
				colvarTypeID.DefaultSetting = @"";
				colvarTypeID.ForeignKeyTableName = "";
				schema.Columns.Add(colvarTypeID);
				
				TableSchema.TableColumn colvarTypeName = new TableSchema.TableColumn(schema);
				colvarTypeName.ColumnName = "TypeName";
				colvarTypeName.DataType = DbType.AnsiString;
				colvarTypeName.MaxLength = 50;
				colvarTypeName.AutoIncrement = false;
				colvarTypeName.IsNullable = true;
				colvarTypeName.IsPrimaryKey = false;
				colvarTypeName.IsForeignKey = false;
				colvarTypeName.IsReadOnly = false;
				colvarTypeName.DefaultSetting = @"";
				colvarTypeName.ForeignKeyTableName = "";
				schema.Columns.Add(colvarTypeName);
				
				TableSchema.TableColumn colvarDescription = new TableSchema.TableColumn(schema);
				colvarDescription.ColumnName = "Description";
				colvarDescription.DataType = DbType.AnsiString;
				colvarDescription.MaxLength = 50;
				colvarDescription.AutoIncrement = false;
				colvarDescription.IsNullable = true;
				colvarDescription.IsPrimaryKey = false;
				colvarDescription.IsForeignKey = false;
				colvarDescription.IsReadOnly = false;
				colvarDescription.DefaultSetting = @"";
				colvarDescription.ForeignKeyTableName = "";
				schema.Columns.Add(colvarDescription);
				
				BaseSchema = schema;
				//add this schema to the provider
				//so we can query it later
				DataService.Providers["DianDang"].AddSchema("DDCertTypes",schema);
			}
		}
		#endregion
		
		#region Props
		  
		[XmlAttribute("TypeID")]
		[Bindable(true)]
		public int TypeID 
		{
			get { return GetColumnValue<int>(Columns.TypeID); }
			set { SetColumnValue(Columns.TypeID, value); }
		}
		  
		[XmlAttribute("TypeName")]
		[Bindable(true)]
		public string TypeName 
		{
			get { return GetColumnValue<string>(Columns.TypeName); }
			set { SetColumnValue(Columns.TypeName, value); }
		}
		  
		[XmlAttribute("Description")]
		[Bindable(true)]
		public string Description 
		{
			get { return GetColumnValue<string>(Columns.Description); }
			set { SetColumnValue(Columns.Description, value); }
		}
		
		#endregion
		
		
			
		
		//no foreign key tables defined (0)
		
		
		
		//no ManyToMany tables defined (0)
		
        
        
		#region ObjectDataSource support
		
		
		/// <summary>
		/// Inserts a record, can be used with the Object Data Source
		/// </summary>
		public static void Insert(string varTypeName,string varDescription)
		{
			DDCertType item = new DDCertType();
			
			item.TypeName = varTypeName;
			
			item.Description = varDescription;
			
		
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		
		/// <summary>
		/// Updates a record, can be used with the Object Data Source
		/// </summary>
		public static void Update(int varTypeID,string varTypeName,string varDescription)
		{
			DDCertType item = new DDCertType();
			
				item.TypeID = varTypeID;
			
				item.TypeName = varTypeName;
			
				item.Description = varDescription;
			
			item.IsNew = false;
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		#endregion
        
        
        
        #region Typed Columns
        
        
        public static TableSchema.TableColumn TypeIDColumn
        {
            get { return Schema.Columns[0]; }
        }
        
        
        
        public static TableSchema.TableColumn TypeNameColumn
        {
            get { return Schema.Columns[1]; }
        }
        
        
        
        public static TableSchema.TableColumn DescriptionColumn
        {
            get { return Schema.Columns[2]; }
        }
        
        
        
        #endregion
		#region Columns Struct
		public struct Columns
		{
			 public static string TypeID = @"TypeID";
			 public static string TypeName = @"TypeName";
			 public static string Description = @"Description";
						
		}
		#endregion
		
		#region Update PK Collections
		
        #endregion
    
        #region Deep Save
		
        #endregion
	}
}
