using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace DianDang
{
    /// <summary>
    /// Controller class for DDCarInfo
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class DDCarInfoController
    {
        // Preload our schema..
        DDCarInfo thisSchemaLoad = new DDCarInfo();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public DDCarInfoCollection FetchAll()
        {
            DDCarInfoCollection coll = new DDCarInfoCollection();
            Query qry = new Query(DDCarInfo.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public DDCarInfoCollection FetchByID(object CarID)
        {
            DDCarInfoCollection coll = new DDCarInfoCollection().Where("CarID", CarID).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public DDCarInfoCollection FetchByQuery(Query qry)
        {
            DDCarInfoCollection coll = new DDCarInfoCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object CarID)
        {
            return (DDCarInfo.Delete(CarID) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object CarID)
        {
            return (DDCarInfo.Destroy(CarID) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(string LicenseNumber,string CarType,string EngineNumber,string CarcaseNumber,string InsuranceDate,string RoadtollDate,string CheckDate,int? PawnageID)
	    {
		    DDCarInfo item = new DDCarInfo();
		    
            item.LicenseNumber = LicenseNumber;
            
            item.CarType = CarType;
            
            item.EngineNumber = EngineNumber;
            
            item.CarcaseNumber = CarcaseNumber;
            
            item.InsuranceDate = InsuranceDate;
            
            item.RoadtollDate = RoadtollDate;
            
            item.CheckDate = CheckDate;
            
            item.PawnageID = PawnageID;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(int CarID,string LicenseNumber,string CarType,string EngineNumber,string CarcaseNumber,string InsuranceDate,string RoadtollDate,string CheckDate,int? PawnageID)
	    {
		    DDCarInfo item = new DDCarInfo();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.CarID = CarID;
				
			item.LicenseNumber = LicenseNumber;
				
			item.CarType = CarType;
				
			item.EngineNumber = EngineNumber;
				
			item.CarcaseNumber = CarcaseNumber;
				
			item.InsuranceDate = InsuranceDate;
				
			item.RoadtollDate = RoadtollDate;
				
			item.CheckDate = CheckDate;
				
			item.PawnageID = PawnageID;
				
	        item.Save(UserName);
	    }
    }
}
