using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace DianDang
{
    /// <summary>
    /// Controller class for DDCustomerInfo
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class DDCustomerInfoController
    {
        // Preload our schema..
        DDCustomerInfo thisSchemaLoad = new DDCustomerInfo();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public DDCustomerInfoCollection FetchAll()
        {
            DDCustomerInfoCollection coll = new DDCustomerInfoCollection();
            Query qry = new Query(DDCustomerInfo.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public DDCustomerInfoCollection FetchByID(object CustomerID)
        {
            DDCustomerInfoCollection coll = new DDCustomerInfoCollection().Where("CustomerID", CustomerID).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public DDCustomerInfoCollection FetchByQuery(Query qry)
        {
            DDCustomerInfoCollection coll = new DDCustomerInfoCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object CustomerID)
        {
            return (DDCustomerInfo.Delete(CustomerID) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object CustomerID)
        {
            return (DDCustomerInfo.Destroy(CustomerID) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(string CustomerName,string PhoneNumber,string Address,string ContactPerson,int? CertTypeID,string CertNumber)
	    {
		    DDCustomerInfo item = new DDCustomerInfo();
		    
            item.CustomerName = CustomerName;
            
            item.PhoneNumber = PhoneNumber;
            
            item.Address = Address;
            
            item.ContactPerson = ContactPerson;
            
            item.CertTypeID = CertTypeID;
            
            item.CertNumber = CertNumber;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(int CustomerID,string CustomerName,string PhoneNumber,string Address,string ContactPerson,int? CertTypeID,string CertNumber)
	    {
		    DDCustomerInfo item = new DDCustomerInfo();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.CustomerID = CustomerID;
				
			item.CustomerName = CustomerName;
				
			item.PhoneNumber = PhoneNumber;
				
			item.Address = Address;
				
			item.ContactPerson = ContactPerson;
				
			item.CertTypeID = CertTypeID;
				
			item.CertNumber = CertNumber;
				
	        item.Save(UserName);
	    }
    }
}
