using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace DianDang
{
	/// <summary>
	/// Strongly-typed collection for the DDGeneralParemeter class.
	/// </summary>
    [Serializable]
	public partial class DDGeneralParemeterCollection : ActiveList<DDGeneralParemeter, DDGeneralParemeterCollection>
	{	   
		public DDGeneralParemeterCollection() {}
        
        /// <summary>
		/// Filters an existing collection based on the set criteria. This is an in-memory filter
		/// Thanks to developingchris for this!
        /// </summary>
        /// <returns>DDGeneralParemeterCollection</returns>
		public DDGeneralParemeterCollection Filter()
        {
            for (int i = this.Count - 1; i > -1; i--)
            {
                DDGeneralParemeter o = this[i];
                foreach (SubSonic.Where w in this.wheres)
                {
                    bool remove = false;
                    System.Reflection.PropertyInfo pi = o.GetType().GetProperty(w.ColumnName);
                    if (pi.CanRead)
                    {
                        object val = pi.GetValue(o, null);
                        switch (w.Comparison)
                        {
                            case SubSonic.Comparison.Equals:
                                if (!val.Equals(w.ParameterValue))
                                {
                                    remove = true;
                                }
                                break;
                        }
                    }
                    if (remove)
                    {
                        this.Remove(o);
                        break;
                    }
                }
            }
            return this;
        }
		
		
	}
	/// <summary>
	/// This is an ActiveRecord class which wraps the DDGeneralParemeters table.
	/// </summary>
	[Serializable]
	public partial class DDGeneralParemeter : ActiveRecord<DDGeneralParemeter>, IActiveRecord
	{
		#region .ctors and Default Settings
		
		public DDGeneralParemeter()
		{
		  SetSQLProps();
		  InitSetDefaults();
		  MarkNew();
		}
		
		private void InitSetDefaults() { SetDefaults(); }
		
		public DDGeneralParemeter(bool useDatabaseDefaults)
		{
			SetSQLProps();
			if(useDatabaseDefaults)
				ForceDefaults();
			MarkNew();
		}
        
		public DDGeneralParemeter(object keyID)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByKey(keyID);
		}
		 
		public DDGeneralParemeter(string columnName, object columnValue)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByParam(columnName,columnValue);
		}
		
		protected static void SetSQLProps() { GetTableSchema(); }
		
		#endregion
		
		#region Schema and Query Accessor	
		public static Query CreateQuery() { return new Query(Schema); }
		public static TableSchema.Table Schema
		{
			get
			{
				if (BaseSchema == null)
					SetSQLProps();
				return BaseSchema;
			}
		}
		
		private static void GetTableSchema() 
		{
			if(!IsSchemaInitialized)
			{
				//Schema declaration
				TableSchema.Table schema = new TableSchema.Table("DDGeneralParemeters", TableType.Table, DataService.GetInstance("DianDang"));
				schema.Columns = new TableSchema.TableColumnCollection();
				schema.SchemaName = @"dbo";
				//columns
				
				TableSchema.TableColumn colvarParamID = new TableSchema.TableColumn(schema);
				colvarParamID.ColumnName = "ParamID";
				colvarParamID.DataType = DbType.Int32;
				colvarParamID.MaxLength = 0;
				colvarParamID.AutoIncrement = true;
				colvarParamID.IsNullable = false;
				colvarParamID.IsPrimaryKey = true;
				colvarParamID.IsForeignKey = false;
				colvarParamID.IsReadOnly = false;
				colvarParamID.DefaultSetting = @"";
				colvarParamID.ForeignKeyTableName = "";
				schema.Columns.Add(colvarParamID);
				
				TableSchema.TableColumn colvarParamName = new TableSchema.TableColumn(schema);
				colvarParamName.ColumnName = "ParamName";
				colvarParamName.DataType = DbType.AnsiString;
				colvarParamName.MaxLength = 50;
				colvarParamName.AutoIncrement = false;
				colvarParamName.IsNullable = true;
				colvarParamName.IsPrimaryKey = false;
				colvarParamName.IsForeignKey = false;
				colvarParamName.IsReadOnly = false;
				colvarParamName.DefaultSetting = @"";
				colvarParamName.ForeignKeyTableName = "";
				schema.Columns.Add(colvarParamName);
				
				TableSchema.TableColumn colvarParamValue = new TableSchema.TableColumn(schema);
				colvarParamValue.ColumnName = "ParamValue";
				colvarParamValue.DataType = DbType.String;
				colvarParamValue.MaxLength = 10;
				colvarParamValue.AutoIncrement = false;
				colvarParamValue.IsNullable = true;
				colvarParamValue.IsPrimaryKey = false;
				colvarParamValue.IsForeignKey = false;
				colvarParamValue.IsReadOnly = false;
				colvarParamValue.DefaultSetting = @"";
				colvarParamValue.ForeignKeyTableName = "";
				schema.Columns.Add(colvarParamValue);
				
				BaseSchema = schema;
				//add this schema to the provider
				//so we can query it later
				DataService.Providers["DianDang"].AddSchema("DDGeneralParemeters",schema);
			}
		}
		#endregion
		
		#region Props
		  
		[XmlAttribute("ParamID")]
		[Bindable(true)]
		public int ParamID 
		{
			get { return GetColumnValue<int>(Columns.ParamID); }
			set { SetColumnValue(Columns.ParamID, value); }
		}
		  
		[XmlAttribute("ParamName")]
		[Bindable(true)]
		public string ParamName 
		{
			get { return GetColumnValue<string>(Columns.ParamName); }
			set { SetColumnValue(Columns.ParamName, value); }
		}
		  
		[XmlAttribute("ParamValue")]
		[Bindable(true)]
		public string ParamValue 
		{
			get { return GetColumnValue<string>(Columns.ParamValue); }
			set { SetColumnValue(Columns.ParamValue, value); }
		}
		
		#endregion
		
		
			
		
		//no foreign key tables defined (0)
		
		
		
		//no ManyToMany tables defined (0)
		
        
        
		#region ObjectDataSource support
		
		
		/// <summary>
		/// Inserts a record, can be used with the Object Data Source
		/// </summary>
		public static void Insert(string varParamName,string varParamValue)
		{
			DDGeneralParemeter item = new DDGeneralParemeter();
			
			item.ParamName = varParamName;
			
			item.ParamValue = varParamValue;
			
		
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		
		/// <summary>
		/// Updates a record, can be used with the Object Data Source
		/// </summary>
		public static void Update(int varParamID,string varParamName,string varParamValue)
		{
			DDGeneralParemeter item = new DDGeneralParemeter();
			
				item.ParamID = varParamID;
			
				item.ParamName = varParamName;
			
				item.ParamValue = varParamValue;
			
			item.IsNew = false;
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		#endregion
        
        
        
        #region Typed Columns
        
        
        public static TableSchema.TableColumn ParamIDColumn
        {
            get { return Schema.Columns[0]; }
        }
        
        
        
        public static TableSchema.TableColumn ParamNameColumn
        {
            get { return Schema.Columns[1]; }
        }
        
        
        
        public static TableSchema.TableColumn ParamValueColumn
        {
            get { return Schema.Columns[2]; }
        }
        
        
        
        #endregion
		#region Columns Struct
		public struct Columns
		{
			 public static string ParamID = @"ParamID";
			 public static string ParamName = @"ParamName";
			 public static string ParamValue = @"ParamValue";
						
		}
		#endregion
		
		#region Update PK Collections
		
        #endregion
    
        #region Deep Save
		
        #endregion
	}
}
