using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace DianDang
{
	/// <summary>
	/// Strongly-typed collection for the DDPrintParam class.
	/// </summary>
    [Serializable]
	public partial class DDPrintParamCollection : ActiveList<DDPrintParam, DDPrintParamCollection>
	{	   
		public DDPrintParamCollection() {}
        
        /// <summary>
		/// Filters an existing collection based on the set criteria. This is an in-memory filter
		/// Thanks to developingchris for this!
        /// </summary>
        /// <returns>DDPrintParamCollection</returns>
		public DDPrintParamCollection Filter()
        {
            for (int i = this.Count - 1; i > -1; i--)
            {
                DDPrintParam o = this[i];
                foreach (SubSonic.Where w in this.wheres)
                {
                    bool remove = false;
                    System.Reflection.PropertyInfo pi = o.GetType().GetProperty(w.ColumnName);
                    if (pi.CanRead)
                    {
                        object val = pi.GetValue(o, null);
                        switch (w.Comparison)
                        {
                            case SubSonic.Comparison.Equals:
                                if (!val.Equals(w.ParameterValue))
                                {
                                    remove = true;
                                }
                                break;
                        }
                    }
                    if (remove)
                    {
                        this.Remove(o);
                        break;
                    }
                }
            }
            return this;
        }
		
		
	}
	/// <summary>
	/// This is an ActiveRecord class which wraps the DDPrintParam table.
	/// </summary>
	[Serializable]
	public partial class DDPrintParam : ActiveRecord<DDPrintParam>, IActiveRecord
	{
		#region .ctors and Default Settings
		
		public DDPrintParam()
		{
		  SetSQLProps();
		  InitSetDefaults();
		  MarkNew();
		}
		
		private void InitSetDefaults() { SetDefaults(); }
		
		public DDPrintParam(bool useDatabaseDefaults)
		{
			SetSQLProps();
			if(useDatabaseDefaults)
				ForceDefaults();
			MarkNew();
		}
        
		public DDPrintParam(object keyID)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByKey(keyID);
		}
		 
		public DDPrintParam(string columnName, object columnValue)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByParam(columnName,columnValue);
		}
		
		protected static void SetSQLProps() { GetTableSchema(); }
		
		#endregion
		
		#region Schema and Query Accessor	
		public static Query CreateQuery() { return new Query(Schema); }
		public static TableSchema.Table Schema
		{
			get
			{
				if (BaseSchema == null)
					SetSQLProps();
				return BaseSchema;
			}
		}
		
		private static void GetTableSchema() 
		{
			if(!IsSchemaInitialized)
			{
				//Schema declaration
				TableSchema.Table schema = new TableSchema.Table("DDPrintParam", TableType.Table, DataService.GetInstance("DianDang"));
				schema.Columns = new TableSchema.TableColumnCollection();
				schema.SchemaName = @"dbo";
				//columns
				
				TableSchema.TableColumn colvarPrintOption = new TableSchema.TableColumn(schema);
				colvarPrintOption.ColumnName = "PrintOption";
				colvarPrintOption.DataType = DbType.Int32;
				colvarPrintOption.MaxLength = 0;
				colvarPrintOption.AutoIncrement = true;
				colvarPrintOption.IsNullable = false;
				colvarPrintOption.IsPrimaryKey = true;
				colvarPrintOption.IsForeignKey = false;
				colvarPrintOption.IsReadOnly = false;
				colvarPrintOption.DefaultSetting = @"";
				colvarPrintOption.ForeignKeyTableName = "";
				schema.Columns.Add(colvarPrintOption);
				
				TableSchema.TableColumn colvarOptionName = new TableSchema.TableColumn(schema);
				colvarOptionName.ColumnName = "OptionName";
				colvarOptionName.DataType = DbType.AnsiString;
				colvarOptionName.MaxLength = 50;
				colvarOptionName.AutoIncrement = false;
				colvarOptionName.IsNullable = true;
				colvarOptionName.IsPrimaryKey = false;
				colvarOptionName.IsForeignKey = false;
				colvarOptionName.IsReadOnly = false;
				colvarOptionName.DefaultSetting = @"";
				colvarOptionName.ForeignKeyTableName = "";
				schema.Columns.Add(colvarOptionName);
				
				TableSchema.TableColumn colvarOptionValue = new TableSchema.TableColumn(schema);
				colvarOptionValue.ColumnName = "OptionValue";
				colvarOptionValue.DataType = DbType.Int32;
				colvarOptionValue.MaxLength = 0;
				colvarOptionValue.AutoIncrement = false;
				colvarOptionValue.IsNullable = true;
				colvarOptionValue.IsPrimaryKey = false;
				colvarOptionValue.IsForeignKey = false;
				colvarOptionValue.IsReadOnly = false;
				colvarOptionValue.DefaultSetting = @"";
				colvarOptionValue.ForeignKeyTableName = "";
				schema.Columns.Add(colvarOptionValue);
				
				BaseSchema = schema;
				//add this schema to the provider
				//so we can query it later
				DataService.Providers["DianDang"].AddSchema("DDPrintParam",schema);
			}
		}
		#endregion
		
		#region Props
		  
		[XmlAttribute("PrintOption")]
		[Bindable(true)]
		public int PrintOption 
		{
			get { return GetColumnValue<int>(Columns.PrintOption); }
			set { SetColumnValue(Columns.PrintOption, value); }
		}
		  
		[XmlAttribute("OptionName")]
		[Bindable(true)]
		public string OptionName 
		{
			get { return GetColumnValue<string>(Columns.OptionName); }
			set { SetColumnValue(Columns.OptionName, value); }
		}
		  
		[XmlAttribute("OptionValue")]
		[Bindable(true)]
		public int? OptionValue 
		{
			get { return GetColumnValue<int?>(Columns.OptionValue); }
			set { SetColumnValue(Columns.OptionValue, value); }
		}
		
		#endregion
		
		
			
		
		//no foreign key tables defined (0)
		
		
		
		//no ManyToMany tables defined (0)
		
        
        
		#region ObjectDataSource support
		
		
		/// <summary>
		/// Inserts a record, can be used with the Object Data Source
		/// </summary>
		public static void Insert(string varOptionName,int? varOptionValue)
		{
			DDPrintParam item = new DDPrintParam();
			
			item.OptionName = varOptionName;
			
			item.OptionValue = varOptionValue;
			
		
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		
		/// <summary>
		/// Updates a record, can be used with the Object Data Source
		/// </summary>
		public static void Update(int varPrintOption,string varOptionName,int? varOptionValue)
		{
			DDPrintParam item = new DDPrintParam();
			
				item.PrintOption = varPrintOption;
			
				item.OptionName = varOptionName;
			
				item.OptionValue = varOptionValue;
			
			item.IsNew = false;
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		#endregion
        
        
        
        #region Typed Columns
        
        
        public static TableSchema.TableColumn PrintOptionColumn
        {
            get { return Schema.Columns[0]; }
        }
        
        
        
        public static TableSchema.TableColumn OptionNameColumn
        {
            get { return Schema.Columns[1]; }
        }
        
        
        
        public static TableSchema.TableColumn OptionValueColumn
        {
            get { return Schema.Columns[2]; }
        }
        
        
        
        #endregion
		#region Columns Struct
		public struct Columns
		{
			 public static string PrintOption = @"PrintOption";
			 public static string OptionName = @"OptionName";
			 public static string OptionValue = @"OptionValue";
						
		}
		#endregion
		
		#region Update PK Collections
		
        #endregion
    
        #region Deep Save
		
        #endregion
	}
}
