using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace DianDang
{
    /// <summary>
    /// Controller class for DDFeeRate
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class DDFeeRateController
    {
        // Preload our schema..
        DDFeeRate thisSchemaLoad = new DDFeeRate();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public DDFeeRateCollection FetchAll()
        {
            DDFeeRateCollection coll = new DDFeeRateCollection();
            Query qry = new Query(DDFeeRate.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public DDFeeRateCollection FetchByID(object RateID)
        {
            DDFeeRateCollection coll = new DDFeeRateCollection().Where("RateID", RateID).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public DDFeeRateCollection FetchByQuery(Query qry)
        {
            DDFeeRateCollection coll = new DDFeeRateCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object RateID)
        {
            return (DDFeeRate.Delete(RateID) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object RateID)
        {
            return (DDFeeRate.Destroy(RateID) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(string Rate,int? RateType,string Description)
	    {
		    DDFeeRate item = new DDFeeRate();
		    
            item.Rate = Rate;
            
            item.RateType = RateType;
            
            item.Description = Description;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(int RateID,string Rate,int? RateType,string Description)
	    {
		    DDFeeRate item = new DDFeeRate();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.RateID = RateID;
				
			item.Rate = Rate;
				
			item.RateType = RateType;
				
			item.Description = Description;
				
	        item.Save(UserName);
	    }
    }
}
