using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace DianDang
{
    /// <summary>
    /// Controller class for DDUsers
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class DDUserController
    {
        // Preload our schema..
        DDUser thisSchemaLoad = new DDUser();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public DDUserCollection FetchAll()
        {
            DDUserCollection coll = new DDUserCollection();
            Query qry = new Query(DDUser.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public DDUserCollection FetchByID(object UserID)
        {
            DDUserCollection coll = new DDUserCollection().Where("UserID", UserID).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public DDUserCollection FetchByQuery(Query qry)
        {
            DDUserCollection coll = new DDUserCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object UserID)
        {
            return (DDUser.Delete(UserID) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object UserID)
        {
            return (DDUser.Destroy(UserID) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(string UserName,string UserPassword,int? RoleID,string Email,string PhoneNumber,string CertNumber)
	    {
		    DDUser item = new DDUser();
		    
            item.UserName = UserName;
            
            item.UserPassword = UserPassword;
            
            item.RoleID = RoleID;
            
            item.Email = Email;
            
            item.PhoneNumber = PhoneNumber;
            
            item.CertNumber = CertNumber;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(int UserID,string UserName,string UserPassword,int? RoleID,string Email,string PhoneNumber,string CertNumber)
	    {
		    DDUser item = new DDUser();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.UserID = UserID;
				
			item.UserName = UserName;
				
			item.UserPassword = UserPassword;
				
			item.RoleID = RoleID;
				
			item.Email = Email;
				
			item.PhoneNumber = PhoneNumber;
				
			item.CertNumber = CertNumber;
				
	        item.Save(UserName);
	    }
    }
}
