using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace DianDang
{
    /// <summary>
    /// Controller class for DDCertTypes
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class DDCertTypeController
    {
        // Preload our schema..
        DDCertType thisSchemaLoad = new DDCertType();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public DDCertTypeCollection FetchAll()
        {
            DDCertTypeCollection coll = new DDCertTypeCollection();
            Query qry = new Query(DDCertType.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public DDCertTypeCollection FetchByID(object TypeID)
        {
            DDCertTypeCollection coll = new DDCertTypeCollection().Where("TypeID", TypeID).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public DDCertTypeCollection FetchByQuery(Query qry)
        {
            DDCertTypeCollection coll = new DDCertTypeCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object TypeID)
        {
            return (DDCertType.Delete(TypeID) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object TypeID)
        {
            return (DDCertType.Destroy(TypeID) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(string TypeName,string Description)
	    {
		    DDCertType item = new DDCertType();
		    
            item.TypeName = TypeName;
            
            item.Description = Description;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(int TypeID,string TypeName,string Description)
	    {
		    DDCertType item = new DDCertType();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.TypeID = TypeID;
				
			item.TypeName = TypeName;
				
			item.Description = Description;
				
	        item.Save(UserName);
	    }
    }
}
