using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace DianDang
{
    /// <summary>
    /// Controller class for DDStatisticClass
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class DDStatisticClassController
    {
        // Preload our schema..
        DDStatisticClass thisSchemaLoad = new DDStatisticClass();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public DDStatisticClassCollection FetchAll()
        {
            DDStatisticClassCollection coll = new DDStatisticClassCollection();
            Query qry = new Query(DDStatisticClass.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public DDStatisticClassCollection FetchByID(object ClassID)
        {
            DDStatisticClassCollection coll = new DDStatisticClassCollection().Where("ClassID", ClassID).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public DDStatisticClassCollection FetchByQuery(Query qry)
        {
            DDStatisticClassCollection coll = new DDStatisticClassCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object ClassID)
        {
            return (DDStatisticClass.Delete(ClassID) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object ClassID)
        {
            return (DDStatisticClass.Destroy(ClassID) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(string ClassName)
	    {
		    DDStatisticClass item = new DDStatisticClass();
		    
            item.ClassName = ClassName;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(int ClassID,string ClassName)
	    {
		    DDStatisticClass item = new DDStatisticClass();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.ClassID = ClassID;
				
			item.ClassName = ClassName;
				
	        item.Save(UserName);
	    }
    }
}
