using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace DianDang
{
	/// <summary>
	/// Strongly-typed collection for the DDMesureUnit class.
	/// </summary>
    [Serializable]
	public partial class DDMesureUnitCollection : ActiveList<DDMesureUnit, DDMesureUnitCollection>
	{	   
		public DDMesureUnitCollection() {}
        
        /// <summary>
		/// Filters an existing collection based on the set criteria. This is an in-memory filter
		/// Thanks to developingchris for this!
        /// </summary>
        /// <returns>DDMesureUnitCollection</returns>
		public DDMesureUnitCollection Filter()
        {
            for (int i = this.Count - 1; i > -1; i--)
            {
                DDMesureUnit o = this[i];
                foreach (SubSonic.Where w in this.wheres)
                {
                    bool remove = false;
                    System.Reflection.PropertyInfo pi = o.GetType().GetProperty(w.ColumnName);
                    if (pi.CanRead)
                    {
                        object val = pi.GetValue(o, null);
                        switch (w.Comparison)
                        {
                            case SubSonic.Comparison.Equals:
                                if (!val.Equals(w.ParameterValue))
                                {
                                    remove = true;
                                }
                                break;
                        }
                    }
                    if (remove)
                    {
                        this.Remove(o);
                        break;
                    }
                }
            }
            return this;
        }
		
		
	}
	/// <summary>
	/// This is an ActiveRecord class which wraps the DDMesureUnit table.
	/// </summary>
	[Serializable]
	public partial class DDMesureUnit : ActiveRecord<DDMesureUnit>, IActiveRecord
	{
		#region .ctors and Default Settings
		
		public DDMesureUnit()
		{
		  SetSQLProps();
		  InitSetDefaults();
		  MarkNew();
		}
		
		private void InitSetDefaults() { SetDefaults(); }
		
		public DDMesureUnit(bool useDatabaseDefaults)
		{
			SetSQLProps();
			if(useDatabaseDefaults)
				ForceDefaults();
			MarkNew();
		}
        
		public DDMesureUnit(object keyID)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByKey(keyID);
		}
		 
		public DDMesureUnit(string columnName, object columnValue)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByParam(columnName,columnValue);
		}
		
		protected static void SetSQLProps() { GetTableSchema(); }
		
		#endregion
		
		#region Schema and Query Accessor	
		public static Query CreateQuery() { return new Query(Schema); }
		public static TableSchema.Table Schema
		{
			get
			{
				if (BaseSchema == null)
					SetSQLProps();
				return BaseSchema;
			}
		}
		
		private static void GetTableSchema() 
		{
			if(!IsSchemaInitialized)
			{
				//Schema declaration
				TableSchema.Table schema = new TableSchema.Table("DDMesureUnit", TableType.Table, DataService.GetInstance("DianDang"));
				schema.Columns = new TableSchema.TableColumnCollection();
				schema.SchemaName = @"dbo";
				//columns
				
				TableSchema.TableColumn colvarUnitID = new TableSchema.TableColumn(schema);
				colvarUnitID.ColumnName = "UnitID";
				colvarUnitID.DataType = DbType.Int32;
				colvarUnitID.MaxLength = 0;
				colvarUnitID.AutoIncrement = true;
				colvarUnitID.IsNullable = false;
				colvarUnitID.IsPrimaryKey = true;
				colvarUnitID.IsForeignKey = false;
				colvarUnitID.IsReadOnly = false;
				colvarUnitID.DefaultSetting = @"";
				colvarUnitID.ForeignKeyTableName = "";
				schema.Columns.Add(colvarUnitID);
				
				TableSchema.TableColumn colvarUnitName = new TableSchema.TableColumn(schema);
				colvarUnitName.ColumnName = "UnitName";
				colvarUnitName.DataType = DbType.AnsiString;
				colvarUnitName.MaxLength = 50;
				colvarUnitName.AutoIncrement = false;
				colvarUnitName.IsNullable = true;
				colvarUnitName.IsPrimaryKey = false;
				colvarUnitName.IsForeignKey = false;
				colvarUnitName.IsReadOnly = false;
				colvarUnitName.DefaultSetting = @"";
				colvarUnitName.ForeignKeyTableName = "";
				schema.Columns.Add(colvarUnitName);
				
				TableSchema.TableColumn colvarUnitType = new TableSchema.TableColumn(schema);
				colvarUnitType.ColumnName = "UnitType";
				colvarUnitType.DataType = DbType.AnsiString;
				colvarUnitType.MaxLength = 50;
				colvarUnitType.AutoIncrement = false;
				colvarUnitType.IsNullable = true;
				colvarUnitType.IsPrimaryKey = false;
				colvarUnitType.IsForeignKey = false;
				colvarUnitType.IsReadOnly = false;
				colvarUnitType.DefaultSetting = @"";
				colvarUnitType.ForeignKeyTableName = "";
				schema.Columns.Add(colvarUnitType);
				
				TableSchema.TableColumn colvarDescription = new TableSchema.TableColumn(schema);
				colvarDescription.ColumnName = "Description";
				colvarDescription.DataType = DbType.AnsiString;
				colvarDescription.MaxLength = 50;
				colvarDescription.AutoIncrement = false;
				colvarDescription.IsNullable = true;
				colvarDescription.IsPrimaryKey = false;
				colvarDescription.IsForeignKey = false;
				colvarDescription.IsReadOnly = false;
				colvarDescription.DefaultSetting = @"";
				colvarDescription.ForeignKeyTableName = "";
				schema.Columns.Add(colvarDescription);
				
				BaseSchema = schema;
				//add this schema to the provider
				//so we can query it later
				DataService.Providers["DianDang"].AddSchema("DDMesureUnit",schema);
			}
		}
		#endregion
		
		#region Props
		  
		[XmlAttribute("UnitID")]
		[Bindable(true)]
		public int UnitID 
		{
			get { return GetColumnValue<int>(Columns.UnitID); }
			set { SetColumnValue(Columns.UnitID, value); }
		}
		  
		[XmlAttribute("UnitName")]
		[Bindable(true)]
		public string UnitName 
		{
			get { return GetColumnValue<string>(Columns.UnitName); }
			set { SetColumnValue(Columns.UnitName, value); }
		}
		  
		[XmlAttribute("UnitType")]
		[Bindable(true)]
		public string UnitType 
		{
			get { return GetColumnValue<string>(Columns.UnitType); }
			set { SetColumnValue(Columns.UnitType, value); }
		}
		  
		[XmlAttribute("Description")]
		[Bindable(true)]
		public string Description 
		{
			get { return GetColumnValue<string>(Columns.Description); }
			set { SetColumnValue(Columns.Description, value); }
		}
		
		#endregion
		
		
			
		
		//no foreign key tables defined (0)
		
		
		
		//no ManyToMany tables defined (0)
		
        
        
		#region ObjectDataSource support
		
		
		/// <summary>
		/// Inserts a record, can be used with the Object Data Source
		/// </summary>
		public static void Insert(string varUnitName,string varUnitType,string varDescription)
		{
			DDMesureUnit item = new DDMesureUnit();
			
			item.UnitName = varUnitName;
			
			item.UnitType = varUnitType;
			
			item.Description = varDescription;
			
		
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		
		/// <summary>
		/// Updates a record, can be used with the Object Data Source
		/// </summary>
		public static void Update(int varUnitID,string varUnitName,string varUnitType,string varDescription)
		{
			DDMesureUnit item = new DDMesureUnit();
			
				item.UnitID = varUnitID;
			
				item.UnitName = varUnitName;
			
				item.UnitType = varUnitType;
			
				item.Description = varDescription;
			
			item.IsNew = false;
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		#endregion
        
        
        
        #region Typed Columns
        
        
        public static TableSchema.TableColumn UnitIDColumn
        {
            get { return Schema.Columns[0]; }
        }
        
        
        
        public static TableSchema.TableColumn UnitNameColumn
        {
            get { return Schema.Columns[1]; }
        }
        
        
        
        public static TableSchema.TableColumn UnitTypeColumn
        {
            get { return Schema.Columns[2]; }
        }
        
        
        
        public static TableSchema.TableColumn DescriptionColumn
        {
            get { return Schema.Columns[3]; }
        }
        
        
        
        #endregion
		#region Columns Struct
		public struct Columns
		{
			 public static string UnitID = @"UnitID";
			 public static string UnitName = @"UnitName";
			 public static string UnitType = @"UnitType";
			 public static string Description = @"Description";
						
		}
		#endregion
		
		#region Update PK Collections
		
        #endregion
    
        #region Deep Save
		
        #endregion
	}
}
