using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace DianDang
{
	/// <summary>
	/// Strongly-typed collection for the DDSearchOption class.
	/// </summary>
    [Serializable]
	public partial class DDSearchOptionCollection : ActiveList<DDSearchOption, DDSearchOptionCollection>
	{	   
		public DDSearchOptionCollection() {}
        
        /// <summary>
		/// Filters an existing collection based on the set criteria. This is an in-memory filter
		/// Thanks to developingchris for this!
        /// </summary>
        /// <returns>DDSearchOptionCollection</returns>
		public DDSearchOptionCollection Filter()
        {
            for (int i = this.Count - 1; i > -1; i--)
            {
                DDSearchOption o = this[i];
                foreach (SubSonic.Where w in this.wheres)
                {
                    bool remove = false;
                    System.Reflection.PropertyInfo pi = o.GetType().GetProperty(w.ColumnName);
                    if (pi.CanRead)
                    {
                        object val = pi.GetValue(o, null);
                        switch (w.Comparison)
                        {
                            case SubSonic.Comparison.Equals:
                                if (!val.Equals(w.ParameterValue))
                                {
                                    remove = true;
                                }
                                break;
                        }
                    }
                    if (remove)
                    {
                        this.Remove(o);
                        break;
                    }
                }
            }
            return this;
        }
		
		
	}
	/// <summary>
	/// This is an ActiveRecord class which wraps the DDSearchOption table.
	/// </summary>
	[Serializable]
	public partial class DDSearchOption : ActiveRecord<DDSearchOption>, IActiveRecord
	{
		#region .ctors and Default Settings
		
		public DDSearchOption()
		{
		  SetSQLProps();
		  InitSetDefaults();
		  MarkNew();
		}
		
		private void InitSetDefaults() { SetDefaults(); }
		
		public DDSearchOption(bool useDatabaseDefaults)
		{
			SetSQLProps();
			if(useDatabaseDefaults)
				ForceDefaults();
			MarkNew();
		}
        
		public DDSearchOption(object keyID)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByKey(keyID);
		}
		 
		public DDSearchOption(string columnName, object columnValue)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByParam(columnName,columnValue);
		}
		
		protected static void SetSQLProps() { GetTableSchema(); }
		
		#endregion
		
		#region Schema and Query Accessor	
		public static Query CreateQuery() { return new Query(Schema); }
		public static TableSchema.Table Schema
		{
			get
			{
				if (BaseSchema == null)
					SetSQLProps();
				return BaseSchema;
			}
		}
		
		private static void GetTableSchema() 
		{
			if(!IsSchemaInitialized)
			{
				//Schema declaration
				TableSchema.Table schema = new TableSchema.Table("DDSearchOption", TableType.Table, DataService.GetInstance("DianDang"));
				schema.Columns = new TableSchema.TableColumnCollection();
				schema.SchemaName = @"dbo";
				//columns
				
				TableSchema.TableColumn colvarOptionID = new TableSchema.TableColumn(schema);
				colvarOptionID.ColumnName = "OptionID";
				colvarOptionID.DataType = DbType.Int32;
				colvarOptionID.MaxLength = 0;
				colvarOptionID.AutoIncrement = true;
				colvarOptionID.IsNullable = false;
				colvarOptionID.IsPrimaryKey = true;
				colvarOptionID.IsForeignKey = false;
				colvarOptionID.IsReadOnly = false;
				colvarOptionID.DefaultSetting = @"";
				colvarOptionID.ForeignKeyTableName = "";
				schema.Columns.Add(colvarOptionID);
				
				TableSchema.TableColumn colvarOptionName = new TableSchema.TableColumn(schema);
				colvarOptionName.ColumnName = "OptionName";
				colvarOptionName.DataType = DbType.AnsiString;
				colvarOptionName.MaxLength = 50;
				colvarOptionName.AutoIncrement = false;
				colvarOptionName.IsNullable = true;
				colvarOptionName.IsPrimaryKey = false;
				colvarOptionName.IsForeignKey = false;
				colvarOptionName.IsReadOnly = false;
				colvarOptionName.DefaultSetting = @"";
				colvarOptionName.ForeignKeyTableName = "";
				schema.Columns.Add(colvarOptionName);
				
				TableSchema.TableColumn colvarFieldName = new TableSchema.TableColumn(schema);
				colvarFieldName.ColumnName = "FieldName";
				colvarFieldName.DataType = DbType.AnsiString;
				colvarFieldName.MaxLength = 50;
				colvarFieldName.AutoIncrement = false;
				colvarFieldName.IsNullable = true;
				colvarFieldName.IsPrimaryKey = false;
				colvarFieldName.IsForeignKey = false;
				colvarFieldName.IsReadOnly = false;
				colvarFieldName.DefaultSetting = @"";
				colvarFieldName.ForeignKeyTableName = "";
				schema.Columns.Add(colvarFieldName);
				
				TableSchema.TableColumn colvarSearchTypeID = new TableSchema.TableColumn(schema);
				colvarSearchTypeID.ColumnName = "SearchTypeID";
				colvarSearchTypeID.DataType = DbType.Int32;
				colvarSearchTypeID.MaxLength = 0;
				colvarSearchTypeID.AutoIncrement = false;
				colvarSearchTypeID.IsNullable = true;
				colvarSearchTypeID.IsPrimaryKey = false;
				colvarSearchTypeID.IsForeignKey = false;
				colvarSearchTypeID.IsReadOnly = false;
				colvarSearchTypeID.DefaultSetting = @"";
				colvarSearchTypeID.ForeignKeyTableName = "";
				schema.Columns.Add(colvarSearchTypeID);
				
				TableSchema.TableColumn colvarDescription = new TableSchema.TableColumn(schema);
				colvarDescription.ColumnName = "Description";
				colvarDescription.DataType = DbType.AnsiString;
				colvarDescription.MaxLength = 50;
				colvarDescription.AutoIncrement = false;
				colvarDescription.IsNullable = true;
				colvarDescription.IsPrimaryKey = false;
				colvarDescription.IsForeignKey = false;
				colvarDescription.IsReadOnly = false;
				colvarDescription.DefaultSetting = @"";
				colvarDescription.ForeignKeyTableName = "";
				schema.Columns.Add(colvarDescription);
				
				BaseSchema = schema;
				//add this schema to the provider
				//so we can query it later
				DataService.Providers["DianDang"].AddSchema("DDSearchOption",schema);
			}
		}
		#endregion
		
		#region Props
		  
		[XmlAttribute("OptionID")]
		[Bindable(true)]
		public int OptionID 
		{
			get { return GetColumnValue<int>(Columns.OptionID); }
			set { SetColumnValue(Columns.OptionID, value); }
		}
		  
		[XmlAttribute("OptionName")]
		[Bindable(true)]
		public string OptionName 
		{
			get { return GetColumnValue<string>(Columns.OptionName); }
			set { SetColumnValue(Columns.OptionName, value); }
		}
		  
		[XmlAttribute("FieldName")]
		[Bindable(true)]
		public string FieldName 
		{
			get { return GetColumnValue<string>(Columns.FieldName); }
			set { SetColumnValue(Columns.FieldName, value); }
		}
		  
		[XmlAttribute("SearchTypeID")]
		[Bindable(true)]
		public int? SearchTypeID 
		{
			get { return GetColumnValue<int?>(Columns.SearchTypeID); }
			set { SetColumnValue(Columns.SearchTypeID, value); }
		}
		  
		[XmlAttribute("Description")]
		[Bindable(true)]
		public string Description 
		{
			get { return GetColumnValue<string>(Columns.Description); }
			set { SetColumnValue(Columns.Description, value); }
		}
		
		#endregion
		
		
			
		
		//no foreign key tables defined (0)
		
		
		
		//no ManyToMany tables defined (0)
		
        
        
		#region ObjectDataSource support
		
		
		/// <summary>
		/// Inserts a record, can be used with the Object Data Source
		/// </summary>
		public static void Insert(string varOptionName,string varFieldName,int? varSearchTypeID,string varDescription)
		{
			DDSearchOption item = new DDSearchOption();
			
			item.OptionName = varOptionName;
			
			item.FieldName = varFieldName;
			
			item.SearchTypeID = varSearchTypeID;
			
			item.Description = varDescription;
			
		
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		
		/// <summary>
		/// Updates a record, can be used with the Object Data Source
		/// </summary>
		public static void Update(int varOptionID,string varOptionName,string varFieldName,int? varSearchTypeID,string varDescription)
		{
			DDSearchOption item = new DDSearchOption();
			
				item.OptionID = varOptionID;
			
				item.OptionName = varOptionName;
			
				item.FieldName = varFieldName;
			
				item.SearchTypeID = varSearchTypeID;
			
				item.Description = varDescription;
			
			item.IsNew = false;
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		#endregion
        
        
        
        #region Typed Columns
        
        
        public static TableSchema.TableColumn OptionIDColumn
        {
            get { return Schema.Columns[0]; }
        }
        
        
        
        public static TableSchema.TableColumn OptionNameColumn
        {
            get { return Schema.Columns[1]; }
        }
        
        
        
        public static TableSchema.TableColumn FieldNameColumn
        {
            get { return Schema.Columns[2]; }
        }
        
        
        
        public static TableSchema.TableColumn SearchTypeIDColumn
        {
            get { return Schema.Columns[3]; }
        }
        
        
        
        public static TableSchema.TableColumn DescriptionColumn
        {
            get { return Schema.Columns[4]; }
        }
        
        
        
        #endregion
		#region Columns Struct
		public struct Columns
		{
			 public static string OptionID = @"OptionID";
			 public static string OptionName = @"OptionName";
			 public static string FieldName = @"FieldName";
			 public static string SearchTypeID = @"SearchTypeID";
			 public static string Description = @"Description";
						
		}
		#endregion
		
		#region Update PK Collections
		
        #endregion
    
        #region Deep Save
		
        #endregion
	}
}
