using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace DianDang
{
    /// <summary>
    /// Controller class for DDHouseInfo
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class DDHouseInfoController
    {
        // Preload our schema..
        DDHouseInfo thisSchemaLoad = new DDHouseInfo();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public DDHouseInfoCollection FetchAll()
        {
            DDHouseInfoCollection coll = new DDHouseInfoCollection();
            Query qry = new Query(DDHouseInfo.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public DDHouseInfoCollection FetchByID(object HouseID)
        {
            DDHouseInfoCollection coll = new DDHouseInfoCollection().Where("HouseID", HouseID).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public DDHouseInfoCollection FetchByQuery(Query qry)
        {
            DDHouseInfoCollection coll = new DDHouseInfoCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object HouseID)
        {
            return (DDHouseInfo.Delete(HouseID) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object HouseID)
        {
            return (DDHouseInfo.Destroy(HouseID) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(string Address,string CompactNumber,string Area,string RegisterDate,string InsuranceDate,string NotarizationDate,int? PawnageID)
	    {
		    DDHouseInfo item = new DDHouseInfo();
		    
            item.Address = Address;
            
            item.CompactNumber = CompactNumber;
            
            item.Area = Area;
            
            item.RegisterDate = RegisterDate;
            
            item.InsuranceDate = InsuranceDate;
            
            item.NotarizationDate = NotarizationDate;
            
            item.PawnageID = PawnageID;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(int HouseID,string Address,string CompactNumber,string Area,string RegisterDate,string InsuranceDate,string NotarizationDate,int? PawnageID)
	    {
		    DDHouseInfo item = new DDHouseInfo();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.HouseID = HouseID;
				
			item.Address = Address;
				
			item.CompactNumber = CompactNumber;
				
			item.Area = Area;
				
			item.RegisterDate = RegisterDate;
				
			item.InsuranceDate = InsuranceDate;
				
			item.NotarizationDate = NotarizationDate;
				
			item.PawnageID = PawnageID;
				
	        item.Save(UserName);
	    }
    }
}
